services:
  backend:
    build:
      context: ./apps/backend
    image: pidrive-backend:latest
    ports:
      - "8000:4000"
    environment:
      BASE_PATH: /app/data
      ALLOWED_ORIGINS: "${SERVICE_URL_FRONTEND:-http://localhost:3000}"
    volumes:
      - backend_data:/app/data
      - secrets:/secrets
    restart: unless-stopped
    command: sh -c "python3 generate_secrets.py && export $(cat /secrets/.env | xargs) && python -m uvicorn main:app --host 0.0.0.0 --port 4000"

  frontend:
    build:
      context: ./apps/frontend
      args:
        NEXT_PUBLIC_API_URL: "http://backend:4000"
        NEXT_PUBLIC_SITE_URL: "${SERVICE_URL_FRONTEND:-http://localhost:3000}"
        DATABASE_URL: "file:./prisma/prod.db"
    ports:
      - "3000:3000"
    image: pidrive-frontend:latest
    depends_on:
      - backend
    environment:
      DATABASE_URL: "file:./prisma/prod.db"
      NEXT_PUBLIC_UPLOAD_SIZE_LIMIT_GB: "100"
      NEXT_PUBLIC_SITE_URL: "${SERVICE_URL_FRONTEND:-http://localhost:3000}"
      NEXT_PUBLIC_API_URL: "http://backend:4000"
      HOME: "/tmp"
    volumes:
      - frontend_db:/app/prisma
      - secrets:/secrets:ro
    restart: unless-stopped
    command: sh -c "set -a && . /secrets/.env && export NEXT_PUBLIC_API_KEY=$$API_KEY && set +a && npx prisma db push && node server.js"

volumes:
  backend_data:
  frontend_db:
  secrets:
